# Generated by Django 3.1 on 2021-04-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewpost',
            options={'ordering': ['-created']},
        ),
    ]
